  swagger: '2.0'
  info:
    title: Server
    description: Базовый mvp сервер для berserk geroi gym
    version: '1.0'
  tags:
    - name: DeckImport
  consumes:
    - application/json
  produces:
    - application/json
  paths:
    /deck-import/v1/import:
      post:
        summary: Импорт колоды по ссылке на berserkdeck.ru
        operationId: DeckImport_Import
        responses:
          '200':
            description: ''
            schema:
              $ref: '#/definitions/deckImportResponse'
          default:
            description: ''
            schema:
              $ref: '#/definitions/customError'
        parameters:
          - name: body
            in: body
            required: true
            schema:
              $ref: '#/definitions/deckImportRequest'
        tags:
          - DeckImport
  definitions:
    deckImportRequest:
      type: object
      properties:
        id:
          type: number
          title: Числовой id публичной колоды с сайта berserkdeck.ru
    deckImportResponse:
      type: object
      properties:
        id:
          type: number
          title: id колоды
        title:
          type: string
          title: Наименование колоды
        description:
          type: string
          title: Описание колоды
        hero:
          type: object
          title: Карта героя
          $ref: '#/definitions/deckImportDeck'
        deck:
          type: array
          title: Карты колоды
          items:
            $ref: '#/definitions/deckImportDeck'
        sideboard:
          type: array
          title: Карты сайдборда
          items:
            $ref: '#/definitions/deckImportDeck'
    customError:
      type: object
      properties:
        code:
          type: string
          title: Код ошибки
        message:
          type: string
          title: Сообщение
    deckImportDeck:
      type: object
      properties:
        setNumber:
          type: number
          title: Номер сета
        cardNumber:
          type: number
          title: Номер карты
