export const DECK_TITLE_LENGTH_MIN = 1;
export const DECK_TITLE_LENGTH_MAX = 20;

export const DECK_DESCRIPTION_LENGTH_MIN = 0;
export const DECK_DESCRIPTION_LENGTH_MAX = 100;

export const SETTING_AUTO_DEAL_CARDS_COUNT_MIN = 0;
export const SETTING_AUTO_DEAL_CARDS_COUNT_MAX = 4;

export const SETTING_INITIAL_COINT_COUNT_MIN = 0;
export const SETTING_INITIAL_COINT_COUNT_MAX = 20;

export const DATABASE_NAME_LENGTH_MIN = 1;
export const DATABASE_NAME_LENGTH_MAX = 20;

export const CARD_EMPTY_SET_NUMBER = 0;
export const CARD_EMPTY_CARD_NUMBER = 0;
